package remediation

import (
	"fmt"

	"github.com/Zyrakk/nhi-watch/internal/discovery"
)

var knownTemplates = []workloadTemplate{
	{
		name:    "traefik",
		matcher: isTraefik,
		render:  renderTraefik,
	},
	{
		name:    "cert-manager",
		matcher: isCertManager,
		render:  renderCertManager,
	},
}

func renderTraefik(nhi *discovery.NonHumanIdentity) (string, error) {
	return fmt.Sprintf(`# PROPOSAL — Review before applying. Generated by nhi-watch.
# Verified against: Traefik v2.x / v3.x on k3s
# Replaces cluster-admin binding with least-privilege ClusterRole for Traefik ingress controller.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: %[1]s-least-privilege
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/managed-by: nhi-watch
rules:
  # Core resources for ingress routing
  - apiGroups: [""]
    resources: [services, endpoints, secrets]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [services/status]
    verbs: [update]
  # Ingress resources
  - apiGroups: [networking.k8s.io]
    resources: [ingresses, ingressclasses]
    verbs: [get, list, watch]
  - apiGroups: [networking.k8s.io]
    resources: [ingresses/status]
    verbs: [update]
  # Traefik CRDs
  - apiGroups: [traefik.io, traefik.containo.us]
    resources: ["*"]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: %[1]s-least-privilege
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/managed-by: nhi-watch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: %[1]s-least-privilege
subjects:
  - kind: ServiceAccount
    name: %[1]s
    namespace: %[2]s
`, nhi.Name, nhi.Namespace), nil
}

func renderCertManager(nhi *discovery.NonHumanIdentity) (string, error) {
	return fmt.Sprintf(`# PROPOSAL — Review before applying. Generated by nhi-watch.
# Verified against: cert-manager v1.x on k3s
# Least-privilege ClusterRole for cert-manager controller.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: %[1]s-least-privilege
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/managed-by: nhi-watch
rules:
  # Certificate management
  - apiGroups: [cert-manager.io]
    resources: [certificates, certificaterequests, issuers, clusterissuers]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [cert-manager.io]
    resources: [certificates/status, certificaterequests/status]
    verbs: [update, patch]
  # ACME challenges
  - apiGroups: [acme.cert-manager.io]
    resources: [orders, challenges]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [acme.cert-manager.io]
    resources: [orders/status, challenges/status]
    verbs: [update, patch]
  # Core resources
  - apiGroups: [""]
    resources: [secrets]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [""]
    resources: [events]
    verbs: [create, patch]
  - apiGroups: [""]
    resources: [pods, services]
    verbs: [get, list, watch]
  # Ingress for HTTP-01 challenges
  - apiGroups: [networking.k8s.io]
    resources: [ingresses]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [networking.k8s.io]
    resources: [ingresses/finalizers]
    verbs: [update]
  # Gateway API support
  - apiGroups: [gateway.networking.k8s.io]
    resources: [gateways, httproutes]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: %[1]s-least-privilege
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/managed-by: nhi-watch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: %[1]s-least-privilege
subjects:
  - kind: ServiceAccount
    name: %[1]s
    namespace: %[2]s
`, nhi.Name, nhi.Namespace), nil
}
