package remediation

import (
	"fmt"
	"sort"
	"strings"

	"github.com/Zyrakk/nhi-watch/internal/discovery"
	"github.com/Zyrakk/nhi-watch/internal/models"
	"github.com/Zyrakk/nhi-watch/internal/usage"
)

// standardVerbs are the 6 standard Kubernetes RBAC verbs used when expanding
// wildcard ("*") verb entries for reduction calculation.
var standardVerbs = []string{"get", "list", "watch", "create", "update", "delete"}

// renderFromUsage generates a least-privilege ClusterRole + ClusterRoleBinding
// from observed API usage. Returns "" if no usage data or no observed calls.
func renderFromUsage(nhi *discovery.NonHumanIdentity) (string, error) {
	if nhi.UsageProfile == nil || len(nhi.UsageProfile.Records) == 0 {
		return "", nil
	}

	// 1. Group records by API group -> {resources set, verbs set}
	type groupEntry struct {
		resources map[string]bool
		verbs     map[string]bool
	}
	groups := make(map[string]*groupEntry)

	for _, rec := range nhi.UsageProfile.Records {
		g, ok := groups[rec.APIGroup]
		if !ok {
			g = &groupEntry{
				resources: make(map[string]bool),
				verbs:     make(map[string]bool),
			}
			groups[rec.APIGroup] = g
		}
		g.resources[rec.Resource] = true
		g.verbs[rec.Verb] = true
	}

	// 2. Calculate reduction % if Permissions is available
	reduction := -1 // -1 means not calculable
	if nhi.Permissions != nil && len(nhi.Permissions.Rules) > 0 {
		reduction = calculateReduction(nhi.Permissions.Rules, nhi.UsageProfile.Records)
	}

	// 3. Build YAML
	roleName := nhi.Name + "-observed-usage"
	confidence := nhi.UsageProfile.GetConfidence()

	var b strings.Builder

	// Comment header
	b.WriteString("# PROPOSAL — Review before applying. Generated by nhi-watch.\n")
	b.WriteString(fmt.Sprintf("# Based on %d days of observed API usage (confidence: %s)\n",
		nhi.UsageProfile.ObservationDays, confidence))
	if reduction >= 0 {
		b.WriteString(fmt.Sprintf("# Estimated permission reduction: %d%%\n", reduction))
	}
	b.WriteString("---\n")

	// ClusterRole
	b.WriteString("apiVersion: rbac.authorization.k8s.io/v1\n")
	b.WriteString("kind: ClusterRole\n")
	b.WriteString("metadata:\n")
	b.WriteString(fmt.Sprintf("  name: %s\n", roleName))
	b.WriteString("  labels:\n")
	b.WriteString("    app.kubernetes.io/managed-by: nhi-watch\n")
	b.WriteString("rules:\n")

	// One rule per API group, sorted for deterministic output
	apiGroupKeys := make(map[string]bool, len(groups))
	for k := range groups {
		apiGroupKeys[k] = true
	}
	apiGroups := sortedKeys(apiGroupKeys)
	for _, ag := range apiGroups {
		entry := groups[ag]
		resources := sortedKeys(entry.resources)
		verbs := sortedKeys(entry.verbs)

		quotedAG := ag
		if ag == "" {
			quotedAG = `""`
		}
		b.WriteString(fmt.Sprintf("  - apiGroups: [%s]\n", quotedAG))
		b.WriteString(fmt.Sprintf("    resources: [%s]\n", strings.Join(resources, ", ")))
		b.WriteString(fmt.Sprintf("    verbs: [%s]\n", strings.Join(verbs, ", ")))
	}

	// ClusterRoleBinding
	b.WriteString("---\n")
	b.WriteString("apiVersion: rbac.authorization.k8s.io/v1\n")
	b.WriteString("kind: ClusterRoleBinding\n")
	b.WriteString("metadata:\n")
	b.WriteString(fmt.Sprintf("  name: %s\n", roleName))
	b.WriteString("  labels:\n")
	b.WriteString("    app.kubernetes.io/managed-by: nhi-watch\n")
	b.WriteString("roleRef:\n")
	b.WriteString("  apiGroup: rbac.authorization.k8s.io\n")
	b.WriteString("  kind: ClusterRole\n")
	b.WriteString(fmt.Sprintf("  name: %s\n", roleName))
	b.WriteString("subjects:\n")
	b.WriteString("  - kind: ServiceAccount\n")
	b.WriteString(fmt.Sprintf("    name: %s\n", nhi.Name))
	b.WriteString(fmt.Sprintf("    namespace: %s\n", nhi.Namespace))

	return b.String(), nil
}

// calculateReduction estimates the percentage of current permissions not
// observed in usage. It expands wildcard verbs ("*") to the 6 standard verbs
// and handles wildcard resources ("*") by matching any observed resource for
// that verb. Returns (unused / total) * 100.
func calculateReduction(current []models.ResolvedRule, observed []usage.UsageRecord) int {
	// Build set of current verb+resource pairs, tracking wildcard resources
	// separately. A wildcard resource means the verb grants access to all
	// resources, so any observed pair with that verb should count as matched.
	currentPairs := make(map[string]bool)  // explicit verb/resource pairs
	wildcardVerbs := make(map[string]bool) // verbs that have resource "*"

	for _, rule := range current {
		verbs := rule.Verbs
		if containsString(verbs, "*") {
			verbs = standardVerbs
		}
		for _, v := range verbs {
			for _, r := range rule.Resources {
				if r == "*" {
					wildcardVerbs[v] = true
				} else {
					currentPairs[v+"/"+r] = true
				}
			}
		}
	}

	// Total permission count: each explicit pair counts as 1, each wildcard
	// verb counts as 1 (representing unbounded resource access for that verb).
	totalCurrent := len(currentPairs) + len(wildcardVerbs)
	if totalCurrent == 0 {
		return 0
	}

	// Build set of observed verb+resource pairs
	observedPairs := make(map[string]bool)
	observedVerbs := make(map[string]bool)
	for _, rec := range observed {
		observedPairs[rec.Verb+"/"+rec.Resource] = true
		observedVerbs[rec.Verb] = true
	}

	// Count matched permissions
	matched := 0

	// Explicit pairs: direct match
	for pair := range currentPairs {
		if observedPairs[pair] {
			matched++
		}
	}

	// Wildcard verbs: matched if any observed record uses that verb
	for v := range wildcardVerbs {
		if observedVerbs[v] {
			matched++
		}
	}

	unused := totalCurrent - matched
	if unused < 0 {
		unused = 0
	}
	return (unused * 100) / totalCurrent
}

// sortedKeys returns the keys of a map[string]bool sorted alphabetically.
func sortedKeys(m map[string]bool) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// containsString checks if a string slice contains the given value.
func containsString(ss []string, val string) bool {
	for _, s := range ss {
		if s == val {
			return true
		}
	}
	return false
}
